Chore/6 base user service
RevatureRideShare/user-service pull request #7
Opened 2019-11-18 19:00 UTC by Astralvix

renamed branch and should be ready to go

2019-11-19 15:22 UTC, jurczakn requested changes

2019-11-19 15:22 UTC, jurczakn commented on src/main/java/com/revature/bean/Car.java
> +		// TODO Auto-generated constructor stub
Remove TODO comment

2019-11-19 15:22 UTC, jurczakn commented on src/main/java/com/revature/bean/User.java
> +		// TODO Auto-generated constructor stub
TODO comment

2019-11-19 15:22 UTC, jurczakn commented on src/main/java/com/revature/bean/User.java
> +
excess spacing

2019-11-19 15:22 UTC, jurczakn commented on src/main/java/com/revature/bean/Car.java
> +
excess spacing

2019-11-19 18:44 UTC, Astralvix commented on src/main/java/com/revature/bean/Car.java
> +
fixed

2019-11-19 18:44 UTC, Astralvix commented on src/main/java/com/revature/bean/User.java
> +
fixed

2019-11-19 18:44 UTC, Astralvix commented on src/main/java/com/revature/bean/User.java
> +		// TODO Auto-generated constructor stub
fixed

2019-11-19 18:44 UTC, Astralvix commented on src/main/java/com/revature/bean/Car.java
> +		// TODO Auto-generated constructor stub
fixed

2019-11-19 18:45 UTC, Astralvix commented on src/main/java/com/revature/bean/User.java
> +		// TODO Auto-generated constructor stub
fixed

2019-11-19 18:48 UTC, Astralvix commented on src/main/java/com/revature/bean/User.java
> +
fixed

2019-11-19 18:48 UTC, Astralvix commented on src/main/java/com/revature/bean/Car.java
> +		// TODO Auto-generated constructor stub
fixed

2019-11-20 14:30 UTC, jurczakn approved these changes
ok

2019-11-20 14:31 UTC, merged